name: Optimize Kernel Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terser
        run: npm install -g terser

      - name: Recode and Optimize Files
        timeout-minutes: 16
        run: |
          find . -type f \( -name '*.c' -o -name '*.h' -o -name 'Makefile*' \) -exec terser --compress --mangle --output {} {} \;

      - name: Zip Optimized Files
        run: zip -r optimized_files.zip .

      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: optimized-files
          path: optimized_files.zip
