name: Optimize Kernel Files

on:
  push:
    branches:
      - main

jobs:
  optimize_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Terser
        run: npm install -g terser

      - name: Recode and Optimize Files
        run: |
          find . -type f -name '*.c' -o -name '*.h' -exec terser --compress --mangle --output {} {} \;

      - name: Zip Optimized Files
        run: zip -r optimized_files.zip .

      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: optimized-files
          path: optimized_files.zip
      
    - name: Merge changes from kernel repo
      run: git merge kernel_repo/main --allow-unrelated-histories
      
    - name: Push changes to base repo
      run: |
        git push origin new_kernel_branch
